version: "3.8"
services:
  hvm:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - FLASK_ENV=production
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
